# Gentoo Kernel CI
#
# After modifying this file check it using: http://lint.travis-ci.org/
#

language: python

python:
#  - "2.7"
  - "3.5"
## work only with python 2 as now

before_install:
  - pip install --upgrade pip
  - pip install treq
  - pip install 'buildbot[bundle]'

# Simply tests the configuration setup.
script:
  - mkdir buildbot
  - cd buildbot
  - buildbot create-master master
  - echo 'test:test' > master/password
  - printf 'kernelci:test\nkernelci2:test' > master/workers.cfg
  - printf 'test' > master/mail_password
  - rm -f master/master.cfg.sample
  - cp ../master.cfg master/.
  - cd master
  - buildbot checkconfig master.cfg
