architecture_testing_list:
 - name: amd64
   toolchain:
   - gcc
   - clang
 - name: arm
   toolchain:
   - gcc
 - name: arm64
   toolchain:
   - gcc
 - name: ppc64
   toolchain:
   - gcc
 - name: sparc
   toolchain:
   - gcc
